### ISSUE TITLE
Besoind

### ISSUE THREAD

**Issue by Tombean** [AnaOprescu/graphJava#1]
Bonsoir. Nous aurions besoin de nouvelles fonctions permettant de gerer :
- Les getters / setters ( accesseurs de manière général pour un point, une arête, l'ensemble des points et l'ensemble des arêtes )
- Pouvoir vérifier qu'un point appartient à une arête
- Pouvoir savoir les sommets d'une arête donnée
- Pouvoir supprimer des points et des arêtes ( et l'ensemble des points ou arêtes aussi )
- Pouvoir savoir si deux arêtes sont adjacentes
- Pouvoir savoir s'il existe un chemin entre 2 points donnés ( savoir si en parcourant des arêtes on peut ou non atteindre une destination )

Bien sûr ce sera à nous d'implémenter les fonctions, mais les avoir dans l'interface graph serait grandement utile.

Merci :)

**Comment by AnaOprescu** [comment]
sorry, now i have seen what you asked me, sorry, i hope now is better
