### ISSUE TITLE
besoin des docs / src des autres classes

### ISSUE THREAD

**Issue by Tombean** [AnaOprescu/graphJava#2]
Bonjour, nous aurions besoin de la doc sur les autres classes ( Edge / Vertex / DirectedEdge / UndirectedEdge ) d'urgence :)

**Comment by AnaOprescu** [comment]
dans quelques min :)

**Comment by AnaOprescu** [comment]
i have put the doc know, this was the only way i found to put it..sorry, i hope it will work
