### ISSUE TITLE
Besoin de supprimer

### ISSUE THREAD

**Issue by Tombean** [AnaOprescu/graphJava#4]
Besoin de supprimer le private Vertex[] vertex ( et sommets ) dans directedEdge et undirectedEdge. Sinon ca plante :(

**Comment by AnaOprescu** [comment]
Tu peux le fairw directement ou tu a besoin de l'archive .jar?

**Comment by Tombean** [comment]
J'ai besoin que ce soit fait dans le jar stp

**Comment by AnaOprescu** [comment]
Supprimer ou changer la en public?

**Comment by Tombean** [comment]
de la supprimer. Tu déclares deux tableaux du meme nom ( vertex ) et l'un deux reste vide et fait tout bugger. Donc supprime la déclaration private Vertex[] vertex des classes héritant de Edge

Et pour la classe où tu appelles ça sommets ( UndirectedEdge je crois ) enleve aussi la déclaration de tableau private Vertex[] sommets  et renomme tous les sommets en vertex ( donc this.sommets devient this.vertex )

**Comment by AnaOprescu** [comment]
ddone

**Comment by Tombean** [comment]
Ca fonctionne merci beaucoup :)
